version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha

    working_directory: ~/android-test-securekeys

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      ANDROID_NDK: $HOME/android-ndk-r14
      ANDROID_NDK_HOME: $ANDROID_NDK
      PATH: $PATH:$ANDROID_NDK
      NDK_VERSION: "r14"

    steps:
      - checkout

      - run:
          name: Install NDK
          command: bash ".circleci/install_ndk.sh" "$NDK_VERSION"

      - run:
          name: Install CMAKE
          command: bash ".circleci/install_cmake.sh"

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
            - android-ndk-$NDK_VERSION
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew build