version: 1
machine:
  environment:
    ANDROID_NDK: $HOME/android-ndk-r14
    ANDROID_NDK_HOME: $ANDROID_NDK
    PATH: $PATH:$ANDROID_NDK
    NDK_VERSION: "r14"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
  java:
    version: oraclejdk8

dependencies:
  cache_directories:
    - ~/android-ndk-$NDK_VERSION
  pre:
    - bash ".circleci/install_ndk.sh" "$NDK_VERSION"
    - bash ".circleci/install_cmake.sh"
    - bash ".circleci/install_android.sh"

test:
  override:
    - ./gradlew build --console=plain